version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak-db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - keycloak-network

  keycloak:
    image: bitnami/keycloak:24.0.4
    container_name: keycloak_server
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak-db
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: gemini
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network

volumes:
  postgres:
    name: keycloak_postgres
  keycloak:
    name: keycloak_server
  postgres_data:

networks:
  keycloak-network:
    driver: bridge
