spring:
  application:
    name: gemini-service
  threads:
    virtual:
      enabled: true

spring.data.mongodb:
  uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/?retryWrites=true&w=majority&appName=GeminiDB
  database: gemini-db

logging.level:
  dev.cah1r: info
  org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO
