spring:
  application:
    name: gemini-service
  threads.virtual.enabled: true
  session.jdbc:
      table-name: SPRING_SESSION
  datasource:
    url: jdbc:postgresql://localhost:5432/${GEMINI_DB:gemini_db}
    username: ${GEMINI_USER}
    password: ${GEMINI_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      default_schema: gemini
    hibernate:
      ddl-auto: validate
    open-in-view: false
app.security.jwt:
  signing-key: ${JWT_SIGNING_KEY}
  validity: 3600000

logging.level.dev.cah1r: INFO
